wandb_project: spd-tms
wandb_run_name: null
wandb_run_name_prefix: ""
seed: 0
topk: null
max_sparsity_coeff: 5e-3
pnorm: 0.9
pnorm_end: null
batch_size: 2048
steps: 40_000
print_freq: 5000
lr: 8e-4
lr_schedule: constant
lr_warmup_pct: 0.1
loss_type: param_match
task_config:
  task_name: tms
  k: 5
  n_features: 5
  n_hidden: 2
  n_instances: 12
  bias_val: 0.0
  train_bias: true
  feature_probability: 0.05
  pretrained_model_path: spd/scripts/tms/out/tms_n-features5_n-hidden2_n-instances12.pth