program: spd/scripts/linear/linear_decomposition.py
method: grid
metric:
  name: final_closeness
  goal: minimize
parameters:
  lr:
    values: [1e-2, 1e-4]
  pnorm:
    values: [0.9]
  lp_sparsity_coeff:
    values: [10, 1, 0.1, 0.01]
  steps:
    values: [20_000]
command:
- ${env}
- ${interpreter}
- ${program}
- spd/scripts/linear/linear_match_param_config.yaml