# wandb_project: spd-linear
wandb_run_name: null
wandb_run_name_prefix: ""
seed: 0
batch_size: 1024
steps: 20_000
print_freq: 4000
save_freq: 10_000
lr: 1e-2
max_sparsity_coeff: 1e-1
pnorm: 0.9
pnorm_end: null
lr_scale: constant
lr_warmup_pct: 0.1
sparsity_loss_type: jacobian
sparsity_warmup_pct: 0.0
loss_type: param_match
torch_model_config:
  torch_model_type: deep_linear
  # n_features: 5
  # n_layers: 3
  # n_instances: 2
  pretrained_model_path: spd/scripts/linear/out/linear.pt